<?php

return [
    'copy' => [
        'home_hero_image' => ['label' => 'Hero image URL', 'default' => '/images/mountain-perspective.jpg'],
        'home_hero_image_alt' => ['label' => 'Hero image description', 'default' => 'Sunlight over a mountain landscape, symbolising a new perspective'],
        'home_hero_quote' => ['label' => 'Hero image statement', 'default' => 'Your potential. A world of possibility.'],
        'home_hero_top_label' => ['label' => 'Hero top caption', 'default' => 'THINK DIFFERENTLY. BECOME MORE.'],
        'home_hero_quote_label' => ['label' => 'Hero statement label', 'default' => 'THE NEXT CHAPTER'],
        'home_hero_caption' => ['label' => 'Hero bottom caption', 'default' => 'A NEW PERSPECTIVE CHANGES EVERYTHING'],
        'home_hero_cta' => ['label' => 'Primary hero button', 'default' => 'Begin your journey'],
        'home_hero_story_label' => ['label' => 'Secondary hero link', 'default' => 'Discover the vision'],
        'home_intro_eyebrow' => ['label' => 'Institute introduction label', 'default' => 'THE HUMAN TRANSFORMATION & WEALTH INSTITUTE'],
        'home_consultation_eyebrow' => ['label' => 'Consultation card label', 'default' => 'CLARITY STARTS HERE'],
        'home_speaking_eyebrow' => ['label' => 'Speaking card label', 'default' => 'IDEAS THAT MOVE PEOPLE'],
        'home_newsletter_eyebrow' => ['label' => 'Newsletter label', 'default' => 'KEEP GROWING'],
        'home_principle_1_title' => ['label' => 'Principle 1 title', 'default' => 'Liberate your mind.'],
        'home_principle_1_body' => ['label' => 'Principle 1 text', 'default' => 'Challenge limiting beliefs. Discover a new way of thinking about what is possible.'],
        'home_principle_2_title' => ['label' => 'Principle 2 title', 'default' => 'Transform your life.'],
        'home_principle_2_body' => ['label' => 'Principle 2 text', 'default' => 'Connect purpose with practical action, personal growth, and meaningful change.'],
        'home_principle_3_title' => ['label' => 'Principle 3 title', 'default' => 'Create a different future.'],
        'home_principle_3_body' => ['label' => 'Principle 3 text', 'default' => 'Explore ideas, entrepreneurship, and the foundations of sustainable wealth.'],
        'home_pathway_1_title' => ['label' => 'Pathway 1 title', 'default' => 'Mindset'],
        'home_pathway_1_body' => ['label' => 'Pathway 1 text', 'default' => 'A fresh perspective'],
        'home_pathway_2_title' => ['label' => 'Pathway 2 title', 'default' => 'Leadership'],
        'home_pathway_2_body' => ['label' => 'Pathway 2 text', 'default' => 'Lead with purpose'],
        'home_pathway_3_title' => ['label' => 'Pathway 3 title', 'default' => 'Entrepreneurship'],
        'home_pathway_3_body' => ['label' => 'Pathway 3 text', 'default' => 'Ideas into possibility'],
        'home_programmes_title' => ['label' => 'Featured programmes heading', 'default' => 'Programmes & masterclasses'],
        'home_books_title' => ['label' => 'Featured books heading', 'default' => 'Books & publications'],
        'home_events_title' => ['label' => 'Upcoming events heading', 'default' => 'Upcoming experiences'],
        'home_testimonials_title' => ['label' => 'Testimonials heading', 'default' => 'Stories of transformation'],
        'home_articles_title' => ['label' => 'Articles heading', 'default' => 'Articles & insights'],
    ],
];
