import {chromium} from '@playwright/test';
import {randomBytes} from 'node:crypto';
import {readFileSync} from 'node:fs';
const credentials=JSON.parse(readFileSync('storage/app/local-admin.json','utf8'));
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
 await page.goto('http://127.0.0.1:8000');
 await page.getByRole('heading',{name:/Liberate/,level:1}).waitFor();
 await page.evaluate(async()=>{const image=new Image();image.src='/images/mountain-perspective.jpg';await image.decode()});
 await page.screenshot({path:'/private/tmp/rich-home-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/private/tmp/rich-home-mobile.png',fullPage:true});
 if(await page.locator('.hero h1').evaluate(e=>e.scrollWidth>e.clientWidth))throw Error('Mobile headline clips');
 const imageResponse=await page.request.get('http://127.0.0.1:8000/images/mountain-perspective.jpg');if(!imageResponse.ok())throw Error('Local hero image missing');
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile horizontal overflow');
 await page.getByRole('button',{name:'Toggle navigation'}).click();
 await page.getByRole('link',{name:'Our story',exact:true}).click();
 await page.getByRole('heading',{name:'About Dr. Rich',exact:true}).waitFor();
 await page.goto('http://127.0.0.1:8000/admin/login');
 await page.getByLabel('Email address').fill(credentials.email);
 await page.getByLabel('Password',{exact:true}).fill(credentials.password);
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.waitForURL('**/admin/dashboard');
 await page.screenshot({path:'/private/tmp/rich-admin-mobile.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Admin mobile horizontal overflow');
 await page.setViewportSize({width:1440,height:1000});
 await page.screenshot({path:'/private/tmp/rich-admin-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Create content'}).click();
 await page.getByLabel('Title',{exact:true}).fill('Browser QA draft');
 await page.getByLabel('Body / answer').fill('Temporary browser verification content.');
 await page.getByRole('button',{name:'Save content',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.goto('http://127.0.0.1:8000/admin/articles');
 const row=page.getByRole('row').filter({hasText:'Browser QA draft'});
 await row.getByRole('button',{name:'Edit'}).click();
 await page.getByLabel('Publishing status').selectOption('published');
 await page.getByRole('button',{name:'Save content',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.goto('http://127.0.0.1:8000/articles/browser-qa-draft');
 await page.getByRole('heading',{name:'Browser QA draft',exact:true}).waitFor();
 await page.goto('http://127.0.0.1:8000/admin/articles');
 await page.getByRole('row').filter({hasText:'Browser QA draft'}).getByRole('button',{name:'Edit'}).click();
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'Delete',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.goto('http://127.0.0.1:8000/admin/users');
 await page.getByRole('button',{name:'Add administrator',exact:true}).click();
 await page.getByLabel('Name',{exact:true}).fill('Browser QA Editor');
 await page.getByLabel('Email',{exact:true}).fill('browser-editor@example.test');
 const temporaryPassword=randomBytes(16).toString('hex');
 await page.getByLabel('Password',{exact:true}).fill(temporaryPassword);
 await page.getByLabel('Confirm password',{exact:true}).fill(temporaryPassword);
 await page.getByRole('button',{name:'Save account',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('row').filter({hasText:'browser-editor@example.test'}).getByRole('button',{name:'Manage access'}).click();
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'Remove',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 if(errors.length)throw Error(errors.join('\n'));
 console.log('Passed: desktop and mobile layouts, mobile navigation, sign in, create/publish/view/delete content; administrator create/remove; no browser errors.');
} finally {await browser.close();}
